"""empty message

Revision ID: 81acff85523d
Revises: b81dc818090b
Create Date: 2024-01-02 14:38:55.606875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81acff85523d'
down_revision = 'b81dc818090b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_name_key', type_='unique')

    with op.batch_alter_table('fav__characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav__characters', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_name_key', ['name'])

    # ### end Alembic commands ###
