"""empty message

Revision ID: b81dc818090b
Revises: 65063e129133
Create Date: 2023-12-30 16:37:25.272554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81dc818090b'
down_revision = '65063e129133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav__characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__characters')
    # ### end Alembic commands ###
